// <auto-generated />
using CRUDExersise.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDExersise.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200503220718_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUDExersise.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmailAlias = "lheinschke",
                            FirstName = "Stewart",
                            LastName = "Heinschke",
                            MiddleName = "Lucilia",
                            Office = "Miami",
                            Region = "South"
                        },
                        new
                        {
                            EmployeeId = 2,
                            EmailAlias = "apietesch",
                            FirstName = "Shayna",
                            LastName = "Pietesch",
                            MiddleName = "Archaimbaud",
                            Office = "DC",
                            Region = "East"
                        },
                        new
                        {
                            EmployeeId = 3,
                            EmailAlias = "pfarrow",
                            FirstName = "Phelia",
                            LastName = "Farrow",
                            MiddleName = "Pavlov",
                            Office = "Lexington",
                            Region = "Central"
                        },
                        new
                        {
                            EmployeeId = 4,
                            EmailAlias = "skembley",
                            FirstName = "Sharron",
                            LastName = "Kembley",
                            MiddleName = "Sherry",
                            Office = "Phoenix",
                            Region = "West"
                        },
                        new
                        {
                            EmployeeId = 5,
                            EmailAlias = "wmunroe",
                            FirstName = "Willard",
                            LastName = "Munroe",
                            MiddleName = "Wally",
                            Office = "Bozeman",
                            Region = "North"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
